export const SET_MAIN = 'SET_MAIN';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SHOW_LOADER = 'SHOW_LOADER';
export const GET_TEAMMATES_DATA = 'GET_TEAMMATES_DATA' ;
export const GET_PENDING_CUSTOMERS = 'GET_PENDING_CUSTOMERS' ;
export const GET_ACTIVE_CUSTOMERS = 'GET_ACTIVE_CUSTOMERS' ;


